version: "3"

services:
  hangman:
    build: "."
    command: hangman
    environment:
      SERVER_ADDRESS: "0.0.0.0"
      SERVER_PORT: "8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/code/hangman
