apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hangman.fullname" . }}
  labels:
    app: hangman
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
      - name: hangman
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["hangman"]
        env:
        - name: "SERVER_ADDRESS"
          valueFrom:
            configMapKeyRef:
              name: {{ include "hangman.fullname" . }}
              key: env.SERVER_ADDRESS
        - name: "SERVER_PORT"
          valueFrom:
            configMapKeyRef:
              name: {{ include "hangman.fullname" . }}
              key: env.SERVER_PORT
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/liveness
          initialDelaySeconds: 5
          periodSeconds: 5
