apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman
  labels:
    app: hangman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
      - name: hangman
        image: hangman
        command: ["hangman"]
        env:
        - name: "SERVER_ADDRESS"
          valueFrom:
            configMapKeyRef:
              name: hangman
              key: env.SERVER_ADDRESS
        - name: "SERVER_PORT"
          valueFrom:
            configMapKeyRef:
              name: hangman
              key: env.SERVER_PORT
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/liveness
          initialDelaySeconds: 5
          periodSeconds: 5
