apiVersion: v1
kind: Service
metadata:
  name: hangman
spec:
  selector:
    app: hangman
  ports:
    - name: hangman
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32555
  type: NodePort
